### PR TITLE
Update word2vec models

### PR DESCRIPTION
**Pull request by danich1**
This PR replaces all the models you and @vincerubinetti  were using to build the website. Honestly this doesn't change much actually just the entries are different and I now have another step that the backend will need to implement. I'll give you the code for this new feat. in another PR.

### CODE REVIEW

**Comment by falquaddoomi** [comment]
Does this change the contents of the models? If so, that's fine, but FYI I'll have to re-run the caching step, which will take a day or two. Let me know if you anticipate more changes to the models in the near future; I'll hold off on updating the cache until you're done.

Also, what is this extra step that the backend will need to implement, out of curiosity?

**Comment by danich1** [comment]
>Does this change the contents of the models? If so, that's fine, but FYI I'll have to re-run the caching step, which will take a day or two.

It changes the model vocabulary by collapsing redundant tokens. Redundant tokens are like this example: `patient`, `human`, `male` and `female` are now replaced with `species_9606`. `species_9606` refers to the concept of humans as 9606 is a taxonomy id to represent humans as a species.  So in practicality terms the vocab for these models should decrease in theory.

>Let me know if you anticipate more changes to the models in the near future; I'll hold off on updating the cache until you're done.

The models in this PR will not change. I need to open an issue to describe the upcoming projected changes, but I will have more models coming (covers full text and preprints). I'll discuss more in a new posted issue on the main website page.

>Also, what is this extra step that the backend will need to implement, out of curiosity?

Following up on my previous explanation. The backend will need to perform a quick concept id check to see if I can replace instances of `species_9606` with `homo sapiens`. I kind of made it seem like this will be complex, but it boils down to a quick dictionary lookup.

**Comment by falquaddoomi** [comment]
Ok, it sounds like the contents of the models have changed, and the way that words are looked up is going to change, so I'm going to hold off on caching common words until things become stable.

I just tested these models with the backend server and it seems the filenames now all have `abstract` in them, causing some loaders that I had configured to look for the old filenames to fail. Are you planning to keep them that way, or is that a temporary change?

**Comment by danich1** [comment]
>I just tested these models with the backend server and it seems the filenames now all have abstract in them, causing some loaders that I had configured to look for the old filenames to fail. Are you planning to keep them that way, or is that a temporary change?

Ah my bad. Which is easier for you: I can either change the model names back and place them in a folder called abstract or I can just leave the model names the same with abstract in them. I'm a fan of the first option more as I'm typing this response, but can do either.

**Comment by danich1** [comment]
Ah I just realized I broke other things on your end. My bad again. Here are the following changes this PR makes:
- [ ] model name change - which can be easily fixed
- [ ] `cusum_changepoint_abstracts.tsv` -> `abstract_changepoints.tsv` (there will be other files like this coming and they will be called fulltext_changepoints.tsv and preprint_changepoints.tsv respectively.
- [ ] `all_tok_frequencies.tsv.xz` -> `all_abstract_tok_frequency.tsv.xz` This file no longer has the frequency field. It will only contain the word_count field. I can make this change on the backend if you'd like. Also the other files will contain the same nomenclature (all_fulltext_tok_frequency.tsv.xz, all_preprint_tok_frequency.tsv.xz)

**Review by falquaddoomi — APPROVED** [review]

**Pull request merged**
